# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190724_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
