# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_define', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
