# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_define', '0003_student_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='insert_time',
            field=models.DateTimeField(auto_now_add=True,default='2019-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
