# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_define', '0004_auto_20190802_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='desc',
            field=models.TextField(verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.IntegerField(verbose_name='性别'),
        ),
    ]
